name: Update Brno GTFS Data

on:
  schedule:
    - cron: '0 3 * * *' # Run every day at 3:00 AM UTC
  workflow_dispatch: # Allow manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Download and Process GTFS
        run: node build.mjs

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Automated GTFS data update: ${{ github.run_id }}"
          file_pattern: "brno/"
